#include <stdlib.h>
#include <windows.h>
#include <iostream>
#include <string>
using namespace std;
void timer(int pause) {
	Sleep(pause);
	cout << ".";
}
void charprint(char input, int pause) {
	Sleep(pause);
	cout << input;
}
void strprint(string input, int pause) {
	Sleep(pause);
	cout << "\033[31m" << input;
}
int main() {
	system("bshift_oldUI.bat");
	system("color 1F");
	cout << "Booting from drive D:\\";
	Sleep(1100);
	cout << "\n";
	Sleep(500);
	cout << "                          ..,,;;;;,,'..                         \n";
	Sleep(10);
	cout << "                     .;lxOKNWWWWWWWWNX0kdc'.                    \n";
	Sleep(10);
	cout << "                  'lkXWMMWXK0kkkkkkOKXNMMWN0d;.                 \n";
	Sleep(10);
	cout << "               .;kXMMWKxc;..        ..,:dONMMW0l.               \n";
	Sleep(10);
	cout << "              ;ONMWKd;.                   'lONMWKl.             \n";
	Sleep(10);
	cout << "            .dNMWKl.                        .:OWMWO,            \n";
	Sleep(10);
	cout << "           'OWMNx.                            .lXMMK:           \n";
	Sleep(10);
	cout << "          'OWMXl.                               ;0MMK;          \n";
	Sleep(10);
	cout << "         .xWMNl                                  ;KMMO'         \n";
	Sleep(10);
	cout << "         :XMMk.                                   lNMWl         \n";
	Sleep(10);
	cout << "        .xMMNc                                    ,0MMk.        \n";
	Sleep(10);
	cout << "        .OMMK;           .;ccccccccccccccccc,     .OMM0'        \n";
	Sleep(10);
	cout << "        .OMMK,           ,KMMMMMMMMMMMMMMMMMNd.   .OMM0'        \n";
	Sleep(10);
	cout << "        .xMMNc           ,KMMMMMMMMMMMMMMMMMMW0:. ,0MMO.        \n";
	Sleep(10);
	cout << "         cNMMk.          ,KMMMMMMMMMMMMMMMMMMMMNx;oNMWo         \n";
	Sleep(10);
	cout << "         .kMMNo          ,KMMMMMMMMMMMMMMMMMMMMMWNNMM0'         \n";
	Sleep(10);
	cout << "          ,0MMNo.        ,KMMMMMMMMMMMMMMMMMMMMMMMMMX:          \n";
	Sleep(10);
	cout << "           ,0WMNOddddddddkNMMMMMMMMMMMMMMMMMMMMMMMMXc           \n";
	Sleep(10);
	cout << "            .xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;            \n";
	Sleep(10);
	cout << "             .:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKo.             \n";
	Sleep(10);
	cout << "               .cONMMMMMMMMMMMMMMMMMMMMMMMMMMW0o.               \n";
	Sleep(10);
	cout << "                  ,oOXWMMMMMMMMMMMMMMMMMMMN0d:.                 \n";
	Sleep(10);
	cout << "                     .:oxOKXWWWWWWWWNX0kdc,.                    \n";
	Sleep(10);
	cout << "                          ..',;;;;,,'..                         \n";
	Sleep(750);
	cout << "\nLOGIN: ";
	Sleep(900);
	charprint('b', 900);
	charprint('a', 65);
	charprint('r', 90);
	charprint('n', 85);
	charprint('e', 50);
	charprint('y', 85);
	charprint('.', 120);
	charprint('c', 95);
	charprint('a', 75);
	charprint('l', 95);
	charprint('h', 110);
	charprint('o', 130);
	charprint('u', 80);
	charprint('n', 50);
	Sleep(50);
	cout << "\nPASSWORD: ";
	charprint('*', 950);
	charprint('*', 80);
	charprint('*', 100);
	charprint('*', 85);
	charprint('*', 75);
	charprint('*', 90);
	charprint('*', 100);
	charprint('*', 105);
	charprint('*', 100);
	charprint('*', 320);
	Sleep(800);
	cout << "\n\nWelcome to BMOS.\n";
	Sleep(1750);
	cout << "\nD:\\users\\barney.calhoun>";
	Sleep(950);
	charprint('c', 100);
	charprint('d', 90);
	charprint(' ', 75);
	charprint('p', 80);
	charprint('r', 75);
	charprint('g', 100);
	Sleep(200);
	cout << "\nD:\\users\\barney.calhoun\\prg>";
	Sleep(800);
	charprint('d', 120);
	charprint('i', 100);
	charprint('r', 90);
	cout << "\n\n";
	Sleep(10);
	cout << "bshift.bat\n";
	Sleep(10);
	cout << "bshift_oldUI.bat\n";
	Sleep(10);
	cout << "calc.exe\n";
	Sleep(10);
	cout << "calender.exe\n";
	Sleep(10);
	cout << "doc.exe\n";
	Sleep(10);
	cout << "hl.exe\n";
	Sleep(10);
	cout << "notepad.exe\n";
	Sleep(10);
	cout << "settings.exe\n";
	Sleep(10);
	cout << "sheet.exe\n";
	Sleep(10);
	cout << "slide.exe\n";
	Sleep(10);
	cout << "snake.exe\n";
	Sleep(10);
	cout << "ziptool.exe\n";
	Sleep(100);
	cout << "\nD:\\users\\barney.calhoun\\prg>";
	Sleep(2100);
	charprint('b', 95);
	charprint('s', 85);
	charprint('h', 80);
	charprint('i', 110);
	charprint('f', 105);
	charprint('t', 85);
	charprint('_', 130);
	charprint('o', 90);
	charprint('l', 85);
	charprint('d', 95);
	charprint('U', 110);
	charprint('I', 100);
	charprint('.', 120);
	charprint('b', 110);
	charprint('a', 95);
	charprint('t', 115);
	cout << "\n\n";
	Sleep(3000);
	cout << "\033[31m" << "UNKNOWN << ";
	strprint("Be ", 95);
	strprint("pre", 100);
	strprint("pared ", 200);
	strprint("for ", 150);
	strprint("un", 90);
	strprint("for", 95);
	strprint("seen ", 110);
	strprint("con", 100);
	strprint("se", 95);
	strprint("quen", 115);
	strprint("ces", 105);
	charprint('.', 800);
	charprint('.', 800);
	charprint('.', 800);
	Sleep(2000);
	cout << "\033[0m" << "\n";
	system("color 1F");
	system("CLS");
	cout << "Program bshift_oldUI.bat executed succsessfully";
	Sleep(10000);
	void exit();
}
